name: Playwright Tests

env:
  PUBLIC_EXTERNAL_API_URL: http://localhost:8080
  PUBLIC_INTERNAL_API_URL: http://localhost:8080
  PUBLIC_USE_MOCK_API_DATA: true

on:
  push:
    branches:
      - main
      - develop
      - master
  pull_request:
    branches:
      - develop
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm clean-install

      - name: Build frontend
        run: npm run build

      - name: Run built frontend
        run: npm run preview &

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            playwright-junit.xml
